
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: settle-db
  namespace: settle
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: settle-db
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: settle/staging/database-app
        property: DATABASE_URL
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: settle-db-migrate
  namespace: settle
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: settle-db-migrate
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: settle/staging/database-migrate
        property: DATABASE_URL
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: settle-redis
  namespace: settle
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: settle-redis
    creationPolicy: Owner
  data:
    - secretKey: REDIS_URL
      remoteRef:
        key: settle/staging/redis
        property: REDIS_URL
