#!/usr/bin/env python3
"""Generates deploy/observability/dashboards/settle-overview.yaml (Grafana dashboard ConfigMap)."""

import json
from pathlib import Path

import yaml

OUT = Path(__file__).resolve().parent.parent / "deploy/observability/dashboards/settle-overview.yaml"
DS = {"type": "prometheus", "uid": "prometheus"}
panels = []


def ts(title, exprs, x, y, w=12, h=8, unit="short"):
    panels.append({
        "type": "timeseries", "title": title, "gridPos": {"x": x, "y": y, "w": w, "h": h}, "datasource": DS,
        "fieldConfig": {"defaults": {"unit": unit}, "overrides": []},
        "targets": [{"expr": e, "legendFormat": lg, "refId": chr(65 + i)} for i, (e, lg) in enumerate(exprs)],
    })


def stat(title, expr, x, y, w=6, h=4, unit="percentunit"):
    panels.append({
        "type": "stat", "title": title, "gridPos": {"x": x, "y": y, "w": w, "h": h}, "datasource": DS,
        "fieldConfig": {"defaults": {"unit": unit}, "overrides": []},
        "targets": [{"expr": expr, "refId": "A"}],
    })


stat("SLO 1 good ratio (1h)", "1 - settle:slo_requests_bad:ratio_rate1h", 0, 0)
stat("Error budget burn rate (1h, x)", "settle:slo_requests_bad:ratio_rate1h / 0.005", 6, 0, unit="none")
stat("Duplicate payouts (bank ledger)", "max(settle_reconciliation_duplicate_payouts)", 12, 0, unit="none")
stat("Oldest queued payout", "max(settle_queue_oldest_job_age_seconds)", 18, 0, unit="s")
ts("Ingress requests by status",
   [('sum by (status) (rate(nginx_ingress_controller_requests{ingress=~"settle-api.*"}[1m]))', "{{status}}")], 0, 4, unit="reqps")
ts("API latency p50 / p99 by route",
   [('histogram_quantile(0.99, sum by (le, route) (rate(settle_http_request_duration_seconds_bucket[5m])))', "p99 {{route}}"),
    ('histogram_quantile(0.5, sum by (le) (rate(settle_http_request_duration_seconds_bucket[5m])))', "p50 all")], 12, 4, unit="s")
ts("5xx ratio by version (release verification signal)",
   [("settle:http_5xx:ratio_rate1m_by_version", "{{version}}")], 0, 12, unit="percentunit")
ts("Postgres connections vs max",
   [('sum(pg_stat_activity_count{datname="settle"})', "in use"),
    ("max(pg_settings_max_connections)", "max_connections"),
    ("sum(settle_db_pool_connections_checked_out)", "checked out by settle-api")], 12, 12)
ts("Payout jobs by outcome", [("sum by (outcome) (rate(settle_jobs_total[5m]))", "{{outcome}}")], 0, 20, unit="ops")
ts("Queue depth", [("max by (queue) (settle_queue_depth)", "{{queue}}")], 12, 20)
ts("Bank calls by result", [("sum by (result) (rate(settle_bank_calls_total[5m]))", "{{result}}")], 0, 28, unit="ops")
ts("Container restarts (10m)",
   [('sum by (pod) (increase(kube_pod_container_status_restarts_total{namespace="settle"}[10m]))', "{{pod}}")], 12, 28)
ts("Running versions", [("count by (version) (settle_build_info)", "{{version}}")], 0, 36)
ts("Payouts reaching the bank < 15 min (1d)", [("settle:payouts_within_15m:ratio_rate1d", "ratio")], 12, 36, unit="percentunit")

dashboard = {"uid": "settle-overview", "title": "settle overview", "schemaVersion": 39, "tags": ["settle"],
             "time": {"from": "now-1h", "to": "now"}, "refresh": "15s", "panels": panels}
cm = {"apiVersion": "v1", "kind": "ConfigMap",
      "metadata": {"name": "settle-dashboard", "namespace": "monitoring", "labels": {"grafana_dashboard": "1"}},
      "data": {"settle-overview.json": json.dumps(dashboard, indent=1)}}
OUT.write_text("# Generated by tools/gen_dashboard.py; loaded by the Grafana sidecar (grafana_dashboard label)\n"
               + yaml.safe_dump(cm, sort_keys=False, width=200))
print(f"{len(panels)} panels -> {OUT}")
